### ISSUE TITLE
jessie upgrade path

### ISSUE THREAD

**Issue by SoundGoof** [SpriteLink/NIPAP#803] opened 2015-06-02 18:08 UTC
I did a upgrade from wheezy to jessie on my dev env today, and i needed to manually install postgresql-9.4-ip4r and upgrade the database from 9.1 to 9.4, what is the upgrade path for this?

```
upgrade to jessie
apt-get install postgresql-9.4-ip4r
pg_ctlcluster stop 9.1 main
pg_dropcluster 9.4 main --stop
pg_upgradecluster 9.1 main
pg_ctlcluster 9.4 main start
aptitude purge ~o
change apache for 2.4 config
profit
```

**Comment by plajjan** [comment] 2015-06-02 19:30
We currently depend on this:
```
Depends: debconf, nipap-common, python (>= 2.7), ${misc:Depends}, python-psycopg2, postgresql (>=9.1) | postgresql-9.1 | postgresql-9.2 | postgresql-9.3 | postgresql-9.4, postgresql-9.1-ip4r (>= 2.0) | postgresql-9.3-ip4r (>= 2.0) | postgresql-9.4-ip4r (>= 2.0), postgresql-contrib | postgresql-contrib-9.3, python-flask, python-flask-xml-rpc, python-flask-compress, python-tornado, python-parsedatetime, python-tz, python-dateutil, python-psutil
```
So it's "postgres" package 9.1 or above, which is just a meta-package for postgresql-9.x, so if you just install "postgres" you would get different versions depending on what distribution and which version of that distribution you are using. postgresql-9.1, 9.2, 9.3 and 9.4 all satisfy our dependency on postgres. For ip4r we match on postgresql-9.1-ip4r, postgresql-9.3-ip4r or postgresql-9.4-ip4r. Now the problem is that there is no way that we can say that we want postgresql-9.4-ip4r when postgresql-9.4 is installed... it just needs to be one version of ip4r. postgresql-9.4-ip4r depends on postgresql-9.4 and similarly for the other versions. Since you can have multiple versions of postgresql installed you can end up with the latest running of postgresql not having the ip4r module but the nipapd dependency on ip4r still being met by an older version.

There is no way for us to depend on a matching versions of ip4r and postgresql unless we build packages specifically for a certain version of Debian / Ubuntu but even then it is difficult as it's possible to install a newer version of postgresql using backports or similar.

Can you list what versions of postgres and ip4r you have installed? Does the above fit your case?

**Comment by plajjan** [comment] 2015-07-17 16:32
I'm going to close this issue as I'm afraid there is nothing we can do about this due to the reasons I explained in my last comment.

**Closed by plajjan** 2015-07-17 16:32 UTC
