### ISSUE TITLE
Searching for 'ord' results in an error

### ISSUE THREAD

**Issue by emil-nasso** [SpriteLink/NIPAP#1112] opened 2016-12-01 07:29 UTC
A picture is worth a thousand words. (I was trying to search by order_id)

![https://dl.dropboxusercontent.com/s/3bzl12bo02idrpu/2016-12-01%20at%2008.27.png](https://dl.dropboxusercontent.com/s/3bzl12bo02idrpu/2016-12-01%20at%2008.27.png)

**Comment by plajjan** [comment] 2016-12-01 17:34
Yupp, dupe of #1054 though ;) so closing this one..

**Closed by plajjan** 2016-12-01 17:34 UTC
